# FunkySk

# The version is to help determine which version this config is. Please don't modify this value.
version: "1.0.1c"

# Print additional information in the console. The developers of FunkySk may ask you to enable this when reporting an error.
debug: false

# Stop any song that the player was listening to when they disconnect. (Recommended to keep enabled)
PlayerDisconnectSong: true

# If the file path couldn't be found, mesage the console about this error.
InvalidFile: true

# Broadcast all the syntax that didn't register to the console.
NotRegisteredSyntax: false

# Converts the Enum's into proper english enums like `FADE_TYPE` will be `fade type` or `fading type` as defined in the english.lang of the jar. (Which can be edited, they parent aliases parsing)
UseEnglishEnums: true

# Disables the message saying FunkySk was enabled.
DisableRegisteredInfo: false